name = "FFTIndexing"
uuid = "71991d8d-1ef0-4564-8bfb-550f91a1a974"
authors = ["Brandon Flores <bsflores@wisc.edu>"]
version = "0.1.1"

[compat]
Aqua = "0.8"
Test = "1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
